/*
 * Generated by JasperReports
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class CashLedger_f83d1594e9874571ac63ceb5e3b284298b2d3c0db2cbf2fafc1055a04d0fbac0 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_size = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_size = (JRFillParameter)pm.get("size");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 11 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "cashledger-logo.png"; //$JR_EXPR_ID=13$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.Integer)parameter_size.getValue())+" row(s)"; //$JR_EXPR_ID=17$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 11 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "cashledger-logo.png"; //$JR_EXPR_ID=13$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.Integer)parameter_size.getValue())+" row(s)"; //$JR_EXPR_ID=17$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 11 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "cashledger-logo.png"; //$JR_EXPR_ID=13$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.Integer)parameter_size.getValue())+" row(s)"; //$JR_EXPR_ID=17$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
